### ISSUE TITLE
FLake in run_ensemble

### ISSUE THREAD

**Issue by jjvenky** [aemon-j/LakeEnsemblR#59]
Likely related to https://github.com/aemon-j/LakeEnsemblR/issues/42 since I'm running Ubuntu 18.04:

```
> wtemp_list <- run_ensemble(config_file = masterConfigFile,
+                            model = c('FLake', 'GLM', 'GOTM', 'Simstrat'),
+                            return_list = TRUE)
Loading obs_file...
FLake: Loading ./FLake/all_meteo_file.dat
Replaced SIMULATION_PARAMS time_step_number 365, with 365
Replaced METEO meteofile 'meteo_file_tmp.dat', with 'meteo_file_tmp.dat'
[1] "FLake_ERROR:   Error in if (verbose) {: argument is not interpretable as logical\n"
Error in file(file, "rt") : cannot open the connection
In addition: Warning message:
In file(file, "rt") :
  cannot open file './FLake/output/output.dat': No such file or directory
```

Is there a way to disable or ignore certain models based OS?

**Comment by robertladwig** [comment]
I have updated FLakeR and the example file in LakeEnsemblR. It should now work for macOS and Linux. Could you please test it again?

See #42 for more details.

**Comment by JFeldbauer** [comment]
FLake is running now on my Linux machine (Linux Mint 19.1)

**Comment by tadhg-moore** [comment]
We are still currently having issues with FLake on Linux but @jjvenky you can run `run_ensemble` without FLake by deleting it within the model argument.

**Comment by jjvenky** [comment]
@tadhg-moore 

Finally got my R upgraded from 3.4.* to 3.6.3. Still Ubuntu 18.04.

With a full reinstall of the all packages as per:

```
devtools::install_github('GLEON/GLM3r')
devtools::install_github('hdugan/glmtools')
devtools::install_github('aemon-j/FLakeR')
devtools::install_github('aemon-j/GOTMr')
devtools::install_github('aemon-j/gotmtools')
devtools::install_github('aemon-j/SimstratR')
devtools::install_github('aemon-j/LakeEnsemblR')
devtools::install_github('aemon-j/MyLakeR')
```

The FLake model is still failing:

```
> wtemp_list <- run_ensemble(config_file = masterConfigFile,
+                            model = c('FLake', 'GLM', 'GOTM', 'Simstrat', 'MyLake'),
+                            return_list = TRUE)
Loading obs_file...
FLake: Loading ./FLake/all_meteo_file.dat
Replaced SIMULATION_PARAMS time_step_number 365, with 365
Replaced METEO meteofile './FLake/all_meteo_file.dat', with 'meteo_file_tmp.dat'
At line 263 of file FLake1D.f90 (unit = 11, file = 'feeagh.nml')
Fortran runtime error: Cannot match namelist object name sediments_on

Error termination. Backtrace:
#0  0x7f78c191d31a
#1  0x7f78c191dec5
#2  0x7f78c191e68d
#3  0x7f78c1a8f460
#4  0x7f78c1a982ff
#5  0x7f78c1a985b8
#6  0x55b4172d2ab8
#7  0x55b4172d65dd
#8  0x7f78c0f7cb96
#9  0x55b4172cbed9
#10  0xffffffffffffffff
Error in file(file, "rt") : cannot open the connection
In addition: Warning message:
In file(file, "rt") :
  cannot open file './FLake/output/output.dat': No such file or directory
```

**Comment by jjvenky** [comment]
[deleted previous message]

I can get FLake to run now under R 3.6.3 and Ubuntu 18.04

```# 4. Run ensemble lake models
wtemp_list <- run_ensemble(config_file = masterConfigFile,
                           model = c('FLake', 'GLM'),
                           return_list = TRUE)
```

I had this same error https://github.com/aemon-j/LakeEnsemblR/issues/42#issuecomment-589574293 but all good now.
